import { IProduct } from "../types/product.type";

export const Products: IProduct[] = [
    {
      codigo: "101 001",
      count: undefined,
      nome: "Equilibrium Sh. 300ml",
      price: 12.0,
      linha: "HOMECARE",
      subLinha: "DAILY CARE",
      estoque: true,
    },
    {
      codigo: "102 001",
      count: undefined,
      nome: "Equilibrium Cond. 300ml",
      price: 12.0,
      estoque: true,
    },
    {
      codigo: "101 003",
      count: undefined,
      nome: "Blond Sh. 300ml",
      price: 12.0,
      estoque: true,
    },
    {
      codigo: "102 003",
      count: undefined,
      nome: "Blond Cond. 300ml",
      price: 12.0,
      estoque: true,
    },
    {
      codigo: "101 006",
      count: undefined,
      nome: "Miracle Sh. 300ml",
      price: 12.0,
      estoque: true,
    },
    {
      codigo: "102 006",
      count: undefined,
      nome: "Miracle Cond. 300ml",
      price: 12.0,
      estoque: true,
    },
    {
      codigo: "101 007",
      count: undefined,
      nome: "Sh. Therapy 300ml",
      price: 17.0,
      estoque: true,
    },
    {
      codigo: "101 038",
      count: undefined,
      nome: "Curly Sh. 300ml",
      price: 12.0,
      estoque: true,
    },
    {
      codigo: "102 036",
      count: undefined,
      nome: "Curly Cond. 300ml",
      price: 12.0,
      estoque: true,
    },
    {
      codigo: "101 038",
      count: undefined,
      nome: "Infusion Sh. 300ml",
      price: 12.0,
      estoque: true,
    },
    {
      codigo: "102 036",
      count: undefined,
      nome: "Infusion Cond. 300ml",
      price: 12.0,
      estoque: true,
    },
    {
      codigo: "102 037",
      count: undefined,
      nome: "Miracle Summer Shampoo. 300ml",
      price: 12.0,
      estoque: true,
    },
    {
      codigo: "102 035",
      count: undefined,
      nome: "Miracle Summer Cond. 300ml",
      price: 12.0,
      estoque: true,
    },
    {
      codigo: "103 010",
      count: undefined,
      nome: "Blond Mask 180g",
      price: 17.5,
      subLinha: "WEEKLY CARE",
      estoque: true,
    },
    {
      codigo: "103 003",
      count: undefined,
      nome: "Miracle Mask 180g",
      price: 17.5,
      estoque: true,
    },
    {
      codigo: "2400",
      count: undefined,
      nome: "Mini Net Mask 30g",
      price: 3.5,
      estoque: true,
    },
    {
      codigo: "103 016",
      count: undefined,
      nome: "Net Mask 550g",
      price: 25.0,
      estoque: true,
    },
    {
      codigo: "104 012",
      count: undefined,
      nome: "Night Spa Serum 250ml",
      price: 34.0,
      estoque: true,
    },
    {
      codigo: "104 002",
      count: undefined,
      nome: "Deluxe Prime 260ml",
      price: 23.0,
      estoque: true,
    },
    {
      codigo: "104 028",
      count: undefined,
      nome: "Deluxe Prime Champagne Blond 260ml",
      price: 26.5,
      estoque: true,
    },
    {
      codigo: "104 040",
      count: undefined,
      nome: "Deluxe Prime Summer 260ml",
      price: 26.5,
      estoque: true,
    },
    {
      codigo: "305 024",
      count: undefined,
      nome: "Hair Protector 250ml",
      price: 16.5,
      subLinha: "FINISH",
      estoque: true,
    },
    {
      codigo: "305 032",
      count: undefined,
      nome: "Curly Fix 250ml",
      price: 16.5,
      estoque: true,
    },
    {
      codigo: "313 012",
      count: undefined,
      nome: "Fluid Fix 250ml",
      price: 16.5,
      estoque: true,
    },
    {
      codigo: "305 023",
      count: undefined,
      nome: "Instant Repair 45ml",
      price: 16.5,
      estoque: true,
    },
    {
      codigo: "305 034",
      count: undefined,
      nome: "Curly Twist 650ml",
      price: 43.0,
      estoque: true,
    },
    {
      codigo: "313 013",
      count: undefined,
      nome: "Beach Waves 260ml",
      price: 27.5,
      estoque: true,
    },
    {
      codigo: "211 044",
      count: undefined,
      nome: "Kit Fast Repair (3 Produtos)",
      price: 135.0,
      linha: "PROFISSIONAL",
      subLinha: "BACK BAR ESSENTIALS - MIRACLE",
      estoque: true,
    },
    {
      codigo: "710",
      count: undefined,
      nome: "Kit Perfect Balayage (3 Produtos)",
      price: 201.0,
      estoque: true,
    },
    {
      codigo: "201 011",
      count: undefined,
      nome: "Bidimensional Sh. 1000ml",
      price: 45.0,
      estoque: true,
    },
    {
      codigo: "201 028",
      count: undefined,
      nome: "No Metal Equalizer Shampoo 1000ml",
      price: 65.0,
      estoque: true,
    },
    {
      codigo: "204 006",
      count: undefined,
      nome: "Lipidic 650ml",
      price: 39.5,
      estoque: true,
    },
    {
      codigo: "203 006",
      count: undefined,
      nome: "Intensive Nutrition 1000ml",
      price: 45.0,
      estoque: true,
    },
    {
      codigo: "201 012",
      count: undefined,
      nome: "Clarifying Sh. 1000ml",
      price: 45.0,
      estoque: true,
    },
    {
      codigo: "205 011",
      count: undefined,
      nome: "Amino Miracle 225ml",
      price: 27.5,
      estoque: true,
    },
    {
      codigo: "201 015",
      count: undefined,
      nome: "Basic Shampoo 2400ml",
      subLinha: "BACK BAR ESSENTIALS",
      price: 78.0,
      estoque: true,
    },
    {
      codigo: "202 014",
      count: undefined,
      nome: "Basic Conditioner 2400ml",
      price: 86.0,
      estoque: true,
    },
    {
      codigo: "201 027",
      count: undefined,
      nome: "Therapy Shampoo 1000ml.",
      price: 45.0,
      estoque: true,
    },
  {
      codigo: "5222",
      count: undefined,
      nome: "Shampoo Infusion 1000ml.",
      price: 50.0,
      estoque: true,
    },
  {
      codigo: "5223",
      count: undefined,
      nome: "Condicionador Infusion 1000ml.",
      price: 52.0,
      estoque: true,
    },
  {
      codigo: "5217",
      count: undefined,
      nome: "Shampoo Equilibirum 1000ml.",
      price: 50.0,
      estoque: true,
    },
    {
      codigo: "204 022",
      count: undefined,
      nome: "8x Powder 200g",
      price: 79.0,
      subLinha: "PERFECT BLOND",
      estoque: true,
    },
    {
      codigo: "409 006",
      count: undefined,
      nome: "Air Libre 500g",
      price: 28.5,
      estoque: true,
    },
    {
      codigo: "409 007",
      count: undefined,
      nome: "Blanc Blond 500g",
      price: 28.5,
      estoque: true,
    },
    {
      codigo: "k.415000",
      count: undefined,
      nome: "Papel Laminado Longo 50 x 11",
      price: 38.5,
      estoque: true,
    },
    {
      codigo: "k.416000",
      count: undefined,
      nome: "Papel Laminado Curto 25 x 11",
      price: 38.5,
      estoque: true,
    },
    {
      codigo: "k.418000",
      count: undefined,
      nome: "Papel Eco Mechas Personalizado (MINIMO 50KG)",
      price: 12.9,
      estoque: false,
    },
    {
      codigo: "k.419000",
      count: undefined,
      nome: "Papel Eco Mechas Normal (1KG)",
      price: 16.5,
      estoque: true,
    },

    {
      codigo: "204 025",
      count: undefined,
      nome: "K. Recovery 650ml",
      price: 81.5,
      subLinha: "RECOVERY ESSENTIALS",
      estoque: true,
    },
    {
      codigo: "211 045",
      count: undefined,
      nome: "Fluid Deep Reconstruction 500ml",
      price: 91.5,
      subLinha: "RECOVERY ESSENTIALS",
      estoque: true,
    },
    {
      codigo: "2000",
      count: undefined,
      nome: "Mini Infusion 60G",
      price: 4.0,
      estoque: true,
    },
    {
      codigo: "203 008",
      count: undefined,
      nome: "Infusion 650ml",
      price: 71.5,
      estoque: true,
    },
    {
      codigo: "210 010",
      count: undefined,
      nome: "High Liss 650ml",
      price: 94.5,
      subLinha: "SMOOTHING TREATMENT",
      estoque: true,
    },
    {
      codigo: "210 011",
      count: undefined,
      nome: "High Liss Blond 650ml",
      price: 101.0,
      estoque: true,
    },
    {
      codigo: "414 001",
      count: undefined,
      nome: "0.43 Natural Copper Golden 60g",
      price: 9.9,
      subLinha: "TONNERS",
      estoque: true,
    },
    {
      codigo: "414 002",
      count: undefined,
      nome: "0.03 Natural Golden 60g",
      price: 9.9,
      estoque: true,
    },
    {
      codigo: "414 003",
      count: undefined,
      nome: "0.034 Natural Golden Copper 60g",
      price: 9.9,
      estoque: true,
    },
    {
      codigo: "414 004",
      count: undefined,
      nome: "10.3 Lightest Golden Blond 60g",
      price: 9.9,
      estoque: true,
    },
    {
      codigo: "414 005",
      count: undefined,
      nome: "10.72 Lightest Burgandy Blonde 60g",
      price: 9.9,
      estoque: true,
    },
    {
      codigo: "414 006",
      count: undefined,
      nome: "10.89 Lightest Pearl Blond 60g",
      price: 9.9,
      estoque: true,
    },
    {
      codigo: "414 008",
      count: undefined,
      nome: "8.73 Light Brown Golden Blonde 60g",
      price: 9.9,
      estoque: true,
    },
    {
      codigo: "414 009",
      count: undefined,
      nome: "11.2 Super High Light Platinum Blonde 60g",
      price: 9.9,
      estoque: true,
    },
    {
      codigo: "414 010",
      count: undefined,
      nome: "11.21 Super High Lift Violet Ash Blonde 60g",
      price: 9.9,
      estoque: true,
    },
    {
      codigo: "407 031",
      count: undefined,
      nome: "5.0 Light Brown 60g",
      price: 9.9,
      subLinha: "PERMANENT",
      estoque: true,
    },
    {
      codigo: "407 032",
      count: undefined,
      nome: "6.0 Dark Blonde 60g",
      price: 9.9,
      estoque: true,
    },
    {
      codigo: "407 033",
      count: undefined,
      nome: "7.0 Medium Blonde 60g",
      price: 9.9,
      estoque: true,
    },
    {
      codigo: "407 034",
      count: undefined,
      nome: "8.0 Light Blonde 60g",
      price: 9.9,
      estoque: true,
    },
    {
      codigo: "407 063",
      count: undefined,
      nome: "9.89 Very Light Pearl Blonde 60g",
      price: 9.9,
      estoque: true,
    },
    {
      codigo: "406 016",
      count: undefined,
      nome: "5.0 Light Brown S/P 60g",
      price: 9.9,
      subLinha: "SEMI PERMANENT",
      estoque: true,
    },
    {
      codigo: "406 017",
      count: undefined,
      nome: "6.0 Dark Blonde S/P 60g",
      price: 9.9,
      estoque: true,
    },
    {
      codigo: "406 018",
      count: undefined,
      nome: "7.0 Medium Blonde S/P 60g",
      price: 9.9,
      estoque: true,
    },
    {
      codigo: "406 019",
      count: undefined,
      nome: "8.0 Light Blonde S/P 60g",
      price: 9.9,
      estoque: true,
    },
    {
      codigo: "406 006",
      count: undefined,
      nome: "6.3 Dark Golden Blonde S/P 60g",
      price: 9.9,
      estoque: true,
    },
    {
      codigo: "406 026",
      count: undefined,
      nome: "9.31 Very Light Golden Beige Blonde S/P 60g",
      price: 9.9,
      estoque: true,
    },
    {
      codigo: "406 010",
      count: undefined,
      nome: "7.7 Medium Chestnut Blonde S/P 60g",
      price: 9.9,
      estoque: true,
    },
    {
      codigo: "406 004",
      count: undefined,
      nome: "6.1 Dark Ash Blonde 60g",
      price: 9.9,
      estoque: true,
    },
    {
      codigo: "406 008",
      count: undefined,
      nome: "6.7 Dark Chestnut Blonde 60g",
      price: 9.9,
      estoque: true,
    },
    {
      codigo: "406 009",
      count: undefined,
      nome: "7.1 Medium Ash Blonde 60g",
      price: 9.9,
      estoque: true,
    },
    {
      codigo: "406 025",
      count: undefined,
      nome: "7.89 Medium Pearl Blonde S/P 60g",
      price: 9.9,
      estoque: true,
    },
    {
      codigo: "85163200",
      count: undefined,
      nome: "PRO 480 GREY BIVOLT 127V-220V - MQ",
      subLinha: "MQ",
      price: 175,
      estoque: true,
    },
    {
      codigo: "85163200.32",
      count: undefined,
      nome: "MODELADOR GOLD 32MM (PINÇA) 220V",
      price: 170,
      estoque: true,
    },
    {
      codigo: "85163200.25",
      count: undefined,
      nome: "MODELADOR GOLD 25MM (PINÇA) 220V",
      price: 170,
      estoque: true,
    },
    {
      codigo: "1911",
      count: undefined,
      nome: "TIMMER PARA SALÃO",
      price: 4.70,
      estoque: true,
    },
    {
      codigo: "1910",
      count: undefined,
      nome: "KIT DE ESCOVAS",
      price: 40,
      estoque: true,
    },
    {
      codigo: "6243",
      count: undefined,
      nome: "CARTELA DE CORES",
      subLinha: "SUPORT MATERIAL",
      price: 42.12,
      estoque: true,
    },
    {
      codigo: "",
      count: undefined,
      nome: "T-SHIRT I LOVE TRUSS",
      price: 10,
      estoque: true,
    },
    {
      codigo: "",
      count: undefined,
      nome: "T-SHIRT TRUSS",
      price: 10,
      estoque: true,
    },
    {
      codigo: "491.1EX",
      count: undefined,
      nome: "HAIRDRESSER CAPE",
      price: 21,
      estoque: true,
    },
    {
      codigo: "533EX",
      count: undefined,
      nome: "AVENTAL",
      price: 20,
      estoque: true,
    },
  ]
